include $(THEOS)/makefiles/common.mk
TWEAK_NAME = TVNCZXTouchAdapter
TVNCZXTouchAdapter_FILES = Adapter.mm
TVNCZXTouchAdapter_CFLAGS = -fobjc-arc -I../vendor/zxtouch/include -I../include-spi
TVNCZXTouchAdapter_FRAMEWORKS = UIKit Foundation IOKit
TVNCZXTouchAdapter_USE_MODULES = 0
include $(THEOS_MAKE_PATH)/tweak.mk
