# SPDX-License-Identifier: GPL-2.0-only
DEVICE_INFO_TASK_GET_SCREEN_SIZE = 1
DEVICE_INFO_TASK_GET_SCREEN_ORIENTATION = 2
DEVICE_INFO_TASK_GET_SCREEN_SCALE = 3
DEVICE_INFO_TASK_GET_DEVICE_INFO = 30
DEVICE_INFO_TASK_GET_BATTERY_INFO = 31
